<template>
    <section class="py-24 md:py-32 bg-white relative">
        <div class="max-w-6xl mx-auto px-6">
            <div class="text-center mb-16">
                <h2 class="text-3xl md:text-4xl font-bold text-slate-900 mb-4">
                    The reward token disrupting DeFi incentives
                </h2>
            </div>

            <div class="grid md:grid-cols-3 gap-6">
                <div
                    v-for="useCase in useCases"
                    :key="useCase.title"
                    class="group bg-white border border-slate-200 rounded-2xl p-8 hover:border-slate-300 hover:shadow-lg transition-all duration-300"
                >
                    <!-- Icon -->
                    <div class="w-14 h-14 rounded-xl bg-prex-50 border border-prex-200 flex items-center justify-center mb-6 text-prex-600 group-hover:border-prex-300 transition-colors">
                        <svg class="w-8 h-8" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" :d="useCase.iconPath" />
                        </svg>
                    </div>

                    <!-- Content -->
                    <h3 class="text-xl font-semibold text-slate-900 mb-3">
                        {{ useCase.title }}
                    </h3>

                    <p class="text-slate-600 text-sm leading-relaxed mb-6">
                        {{ useCase.description }}
                    </p>

                    <!-- Link -->
                    <Link
                        :href="useCase.href"
                        class="inline-flex items-center gap-2 text-prex-600 hover:text-prex-500 text-sm font-medium transition-colors group/link"
                    >
                        Learn more
                        <svg
                            class="w-4 h-4 transition-transform group-hover/link:translate-x-1"
                            fill="none"
                            stroke="currentColor"
                            viewBox="0 0 24 24"
                        >
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
                        </svg>
                    </Link>
                </div>
            </div>
        </div>
    </section>
</template>

<script setup>
import { Link } from '@inertiajs/vue3';

const useCases = [
    {
        title: 'wUSD for Traders',
        description: 'Earn wUSD rewards through your trading activity on Prex Markets. Zero cost basis means every wUSD you earn is pure upside.',
        href: '/earn#traders',
        iconPath: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6',
    },
    {
        title: 'wUSD for Referrers',
        description: 'Refer traders to Prex and earn a share of the wUSD rewards generated by their activity. Build passive income through your network.',
        href: '/earn#referrers',
        iconPath: 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0zm6 3a2 2 0 11-4 0 2 2 0 014 0zM7 10a2 2 0 11-4 0 2 2 0 014 0z',
    },
    {
        title: 'wUSD for Developers',
        description: 'Integrate wUSD into your applications. Access our API to check balances, redemption values, and build on top of the wUSD ecosystem.',
        href: '/developers',
        iconPath: 'M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4',
    },
];
</script>
